<?php include_once('includes/header.php') ?>
    <div id="header-subpage" class="outer treatments-sub">
<!--        <div class="navbox"></div>-->
        <div class="pagetitle trcmsd"><span>Root Canal Treatment</span></div>
        <div class="shape"></div>
    </div>
    <div class="_content4 outer clearafter boxmargin">
        <div class="inner">
            <div class="main-con-box">
                <div class="conforbox">
                    <p><b>What is endodontic treatment?</b><br>"Endo" is the Greek word for “inside” and “odont” is Greek for “tooth.” Endodontic treatment treats the inside of the tooth. To understand endodontic treatment, it helps to know something about the anatomy of the tooth. Inside the tooth, under the white enamel and a hard layer called the dentine, is a soft tissue called the pulp. The pulp contains blood vessels, nerves, and connective tissue and creates the surrounding hard tissues of the tooth during development. The pulp extends from the crown of the tooth to the tip of the roots where it connects to the tissues surrounding the root. The pulp is important during a tooth’s growth and development. However, once a tooth is fully mature it can survive without the pulp, because the tooth continues to be nourished by the tissues surrounding it.</p>
                </div>
                <div class="conforbox">
                    <img src="img/root-canal1.png">
                </div>
            </div>
            <p><b>Why would I need an endodontic procedure?</b><br>Endodontic treatment is necessary when the pulp, the soft tissue inside the root canal, becomes inflamed or infected. The inflammation or infection can have a variety of causes: deep decay, repeated dental procedures on the tooth, or a crack or chip in the tooth. In addition, an injury to a tooth may cause pulp damage even if the tooth has no visible chips or cracks. If pulp inflammation or infection is left untreated, it can cause pain or lead to an abscess.</p>
            
            <p><b>What are the signs of needing endodontic treatment?</b><br>Signs to look for include pain, prolonged sensitivity to heat or cold, tenderness to touch and chewing, discoloration of the tooth, and swelling, drainage and tenderness in the nearby gums. Sometimes, however, there are no symptoms.<br>
                <b>How does endodontic treatment save the tooth?</b><br>The endodontist removes the inflamed or infected pulp, carefully cleans and shapes the inside of the canal, a channel inside the root, then fills and seals the space. Afterwards, your endodontist will restore the tooth and will ask you to return to your dentist, who will place a crown or other restoration on the tooth to protect and restore it to full function. After restoration, the tooth continues to function like any other tooth.
            </p>
            <p><b>Will I feel pain during or after the procedure?</b><br>Many endodontic procedures are performed to relieve the pain of toothaches caused by pulp inflammation or infection. With modern techniques and anaesthetics, most patients report that they are comfortable during the procedure. For the first few days after treatment, your tooth may feel sensitive, especially if there was pain or infection before the procedure. This discomfort can be relieved with over-the-counter or prescription medications. Follow your endodontist’s instructions carefully. Your tooth may continue to feel slightly different from your other teeth for some time after your endodontic treatment is completed. However, if you have severe pain or pressure pain that lasts more than a few days, call your endodontist.<br>Endodontic Procedure<br>Endodontic treatment can often be performed in one or two visits and involves the following steps:</p>
            <img src="img/endodontic1.svg" class="mywidth">
            <ul>
                <li>The endodontist examines and x-rays the tooth, then administers local anaesthetic. After the tooth is numb, the endodontist places a small protective sheet called a “dental dam” over the area to isolate the tooth and keep it clean and free of saliva during the procedure.</li>
                <li>The endodontist makes an opening in the crown of the tooth. Very small instruments are used to clean the pulp from the pulp chamber and root canals and to shape the space for filling.</li>
                <li>After the space is cleaned and shaped, the endodontist fills the root canals with a biocompatible material, usually a rubber-like material called “gutta-percha.” The gutta-percha is placed with an adhesive cement to ensure complete sealing of the root canals. In most cases, either a permanent or a temporary filling is placed to close the opening.<br>If the tooth lacks sufficient structure to hold the restoration in place, your dentist or endodontist may place a post inside the tooth. Ask your dentist or endodontist for more details about the specific restoration planned for your tooth.</li>
                <li>Once the treatment is completed, you will be asked to return for a follow up usually six months after the final visit. This is to ensure that your tooth has healed satisfactorily. Your endodontist will then advise you to return to your dentist to have a crown or other restoration placed on the tooth to protect and restore it to full function.</li>
            </ul>
            
            
            <p><b>How much will the procedure cost?</b><br>The cost varies depending on how complex the problem is and which tooth is affected. Molars are more difficult to treat, the fee is usually more. Most dental insurance policies provide some coverage for endodontic treatment. Generally, endodontic treatment and restoration of the natural tooth are less expensive than the alternative of having the tooth extracted. An extracted tooth must be replaced with a bridge or implant to restore chewing function and prevent adjacent teeth from shifting. These procedures tend to cost more than endodontic treatment and appropriate restoration. With root canal treatment you save your natural teeth and money.</p>
            <p><b>Will the tooth need any special care or additional treatment after endodontic treatment?</b><br>In some cases, your endodontist would advise you not to chew or bite on the treated tooth until you have had it restored by your dentist. The unrestored tooth is susceptible to fracture, so you should see your dentist for a full restoration as soon as possible. Otherwise, you need only practice good oral hygiene, including brushing, flossing, and regular checkups and cleanings. Most endodontically treated teeth last as long as other natural teeth. In a few cases, a tooth that has undergone endodontic treatment does not heal or the pain continues. Occasionally, the tooth may become painful or diseased months or even years after successful treatment. Often when this occurs, redoing the endodontic procedure can save the tooth.</p>
        </div>
    </div>
    <?php include_once('includes/footer.php') ?>